### ISSUE TITLE
TO DO: hook some references in those tecnologies

### ISSUE THREAD

**Issue by baptvit** [helpthx/Hackathon-stefanini#1]
tecnologies
- [x] Python 3.6
- [x] Tensorflow or Keras 
- Libs
   - [x] Numpy
   - [x] Seaborn
   - [x] Matplolib
   - [x] Pandas

**Comment by deyachatterjee** [comment]
Hi, can this issue be assigned to me as well? Do let me know; I am proficient in these algorithms and have worked a lot in them. I would love to understand more and then make a PR. For example, what exactly do you mean by "hook some references"? 
Thanks, Deya.

**Comment by baptvit** [comment]
> Hi, can this issue be assigned to me as well? Do let me know; I am proficient in these algorithms and have worked a lot in them. I would love to understand more and then make a PR. For example, what exactly do you mean by "hook some references"?
> Thanks, Deya.

Ohh Deya, I'm currently participating in a hackathon of IA in Brazil. This issue is juts to remind me to do some researches before the hackathon day(june 29). So I guess you cant help me on this rigth now, but we can start something in near future xD.
Thanks, João
